<?php

namespace SIEBundle\Entity;

/**
 * PuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
